default:
  log_dir: "logs"
  red_list_token: "9bb4facb6d23f48efbf424bb05c0c1ef1cf6f468393bc745d42179ac4aca5fee"
  distribution_path: "resources/Distributions/"
  YearAOH2: 2020
  LIM_GBIF: 10000
  engine_AOH: "terra"
  crosswalk: "Lumbierres"
  RAMmax_GB: 10
  #Development
  access_control_allow_origin: "*"
  #alt_raster_path: "H:/Postdoc/Platform/Elevation_MollweidePlatform.tif"
  #cci1_raster_path: "H:/Postdoc/Platform/ESA-CCI/CCIXXXX_reprojMollweide.tif"
  #cci2_raster_path: "H:/Postdoc/Platform/ESA-CCI/CCI2020_reprojMollweide.tif"
  # Development Victor
  alt_raster_path: "C:/Victor_local/Platform/InProgress/Large_Files/Elevation_MollweidePlatform.tif"
  cci1_raster_path: "C:/Victor_local/Platform/InProgress/Large_Files/CCIXXXX_reprojMollweide.tif"
  cci2_raster_path: "C:/Victor_local/Platform/InProgress/Large_Files/CCI2020_reprojMollweide.tif"
  #Production
  #alt_raster_path: "resources/GLOBEelevation/Elevation_MollweidePlatform.tif"
  #cci1_raster_path: "resources/ESA-CCI/CCIXXXX_reprojMollweide.tif"
  #cci2_raster_path: "resources/ESA-CCI/CCI2020_reprojMollweide.tif"
  #access_control_allow_origin: "http://193.204.79.97"
  #Test
  #alt_raster_path: "/Volumes/SSDINDI/LifeWatch/RedList-LaSapienza/Dataset/GLOBEelevation/GLOBE_projected_Moll.tif"
  #cci1_raster_path: "/Volumes/SSDINDI/LifeWatch/RedList-LaSapienza/Dataset/ESACCI-LC-L4-LCCS-Map-300m-P1Y-2010-v2.0.7cds.nc"
  #cci2_raster_path: "/Volumes/SSDINDI/LifeWatch/RedList-LaSapienza/Dataset/C3S-LC-L4-LCCS-Map-300m-P1Y-2020-v2.1.1.nc"
  #access_control_allow_origin: "*"
  #distribution_path: "/Volumes/SSDINDI/LifeWatch/RedList-LaSapienza/Dataset/Distributions/"
