default:
  log_dir: "logs"
  red_list_token: "9bb4facb6d23f48efbf424bb05c0c1ef1cf6f468393bc745d42179ac4aca5fee"
  distribution_path: "resources/Distributions/"
  #Development
  alt_raster_path: "resources/Raster/alt_Nesoenas.mayeri.tif"
  cci1_raster_path: "resources/Raster/CCI_2010_Nesoenas.mayeri.tif"
  cci2_raster_path: "resources/Raster/CCI_2020_Nesoenas.mayeri.tif"
  access_control_allow_origin: "*"
  #Production
  #alt_raster_path: "resources/Raster/GLOBE_projected_Moll.tif"
  #cci1_raster_path: "resources/Raster/ESACCI-LC-L4-LCCS-Map-300m-P1Y-2010-v2.0.7cds.nc"
  #cci2_raster_path: "resources/Raster/C3S-LC-L4-LCCS-Map-300m-P1Y-2020-v2.1.1.nc"
  #access_control_allow_origin: "http://193.204.79.97"
  #Test
  #alt_raster_path: "/Volumes/SSDINDI/LifeWatch/RedList-LaSapienza/Dataset/GLOBEelevation/GLOBE_projected_Moll.tif"
  #cci1_raster_path: "/Volumes/SSDINDI/LifeWatch/RedList-LaSapienza/Dataset/ESACCI-LC-L4-LCCS-Map-300m-P1Y-2010-v2.0.7cds.nc"
  #cci2_raster_path: "/Volumes/SSDINDI/LifeWatch/RedList-LaSapienza/Dataset/C3S-LC-L4-LCCS-Map-300m-P1Y-2020-v2.1.1.nc"
  #access_control_allow_origin: "*"